-- Durable doctor-to-doctor shift handover workflow.

create table if not exists public.doctor_shift_handovers (
  id bigint generated by default as identity primary key,
  from_doctor_id bigint references public.employees(id) on delete restrict,
  to_doctor_id bigint references public.employees(id) on delete restrict,
  from_doctor_name text not null,
  to_doctor_name text not null,
  status text not null default 'بانتظار الاستلام',
  notes text,
  shift_ended_at timestamptz not null default now(),
  accepted_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.handover_patients (
  id bigint generated by default as identity primary key,
  handover_id bigint not null references public.doctor_shift_handovers(id) on delete cascade,
  patient_id bigint not null references public.patients(id) on delete restrict,
  priority text not null default 'اعتيادي',
  clinical_summary text not null,
  pending_actions text not null,
  received_status text not null default 'بانتظار الاستلام',
  acknowledged_at timestamptz,
  created_at timestamptz not null default now(),
  unique (handover_id, patient_id)
);

create index if not exists idx_shift_handovers_created_at
  on public.doctor_shift_handovers (created_at desc);
create index if not exists idx_shift_handovers_to_doctor_status
  on public.doctor_shift_handovers (to_doctor_name, status);
create index if not exists idx_handover_patients_handover
  on public.handover_patients (handover_id);
create index if not exists idx_handover_patients_patient
  on public.handover_patients (patient_id);

create or replace function public.create_shift_handover(
  p_from_doctor_name text,
  p_to_doctor_name text,
  p_patient_ids bigint[],
  p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  handover_record public.doctor_shift_handovers%rowtype;
  inserted_count integer := 0;
begin
  if nullif(trim(p_from_doctor_name), '') is null or nullif(trim(p_to_doctor_name), '') is null then
    raise exception 'Doctor names are required';
  end if;
  if trim(p_from_doctor_name) = trim(p_to_doctor_name) then
    raise exception 'Doctors must be different';
  end if;
  if coalesce(array_length(p_patient_ids, 1), 0) = 0 then
    raise exception 'At least one patient is required';
  end if;

  insert into public.doctor_shift_handovers (
    from_doctor_name, to_doctor_name, notes
  ) values (
    trim(p_from_doctor_name), trim(p_to_doctor_name), nullif(trim(p_notes), '')
  ) returning * into handover_record;

  insert into public.handover_patients (
    handover_id, patient_id, priority, clinical_summary, pending_actions
  )
  select
    handover_record.id,
    patient.id,
    case
      when patient.entry_type = 'رقود' then 'مرتفع'
      when patient.is_newborn then 'متابعة لصيقة'
      else 'اعتيادي'
    end,
    concat('حالة ', patient.entry_type, ' في قسم ', patient.department),
    case
      when patient.entry_type = 'رقود' then 'مراجعة الخطة العلاجية وحالة الرقود والدفع'
      when patient.is_newborn then 'متابعة العلامات الحيوية وربط المتابعة بملف الأم'
      else 'مراجعة آخر إجراء واستكمال الخطة العلاجية'
    end
  from public.patients patient
  where patient.id = any(p_patient_ids)
    and patient.patient_status <> 'خرجت';

  get diagnostics inserted_count = row_count;
  if inserted_count = 0 then
    raise exception 'No active patients were selected';
  end if;

  insert into public.audit_logs (action, entity_type, entity_id, after_data)
  values (
    'create_shift_handover',
    'doctor_shift_handover',
    handover_record.id::text,
    to_jsonb(handover_record) || jsonb_build_object('patient_count', inserted_count)
  );

  return to_jsonb(handover_record) || jsonb_build_object('patient_count', inserted_count);
end;
$$;

create or replace function public.accept_shift_handover(p_handover_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  handover_record public.doctor_shift_handovers%rowtype;
begin
  select * into handover_record
  from public.doctor_shift_handovers
  where id = p_handover_id
  for update;

  if handover_record.id is null then
    raise exception 'Handover not found';
  end if;

  if handover_record.status <> 'تم الاستلام' then
    update public.doctor_shift_handovers
    set status = 'تم الاستلام', accepted_at = now()
    where id = p_handover_id
    returning * into handover_record;

    update public.handover_patients
    set received_status = 'مستلم', acknowledged_at = now()
    where handover_id = p_handover_id;

    update public.patients patient
    set attending_doctor = handover_record.to_doctor_name
    where patient.id in (
      select handover_patient.patient_id
      from public.handover_patients handover_patient
      where handover_patient.handover_id = p_handover_id
    );

    insert into public.audit_logs (action, entity_type, entity_id, after_data)
    values (
      'accept_shift_handover',
      'doctor_shift_handover',
      handover_record.id::text,
      to_jsonb(handover_record)
    );
  end if;

  return to_jsonb(handover_record);
end;
$$;

alter table public.doctor_shift_handovers enable row level security;
alter table public.handover_patients enable row level security;

revoke all on table public.doctor_shift_handovers, public.handover_patients
  from anon, authenticated;
grant all on table public.doctor_shift_handovers, public.handover_patients
  to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke all on function public.create_shift_handover(text, text, bigint[], text)
  from public, anon, authenticated;
revoke all on function public.accept_shift_handover(bigint)
  from public, anon, authenticated;
grant execute on function public.create_shift_handover(text, text, bigint[], text)
  to service_role;
grant execute on function public.accept_shift_handover(bigint)
  to service_role;

insert into public.app_schema_migrations (version)
values ('202608110002_shift_handovers')
on conflict (version) do nothing;
