-- Real reporting inputs and administrator-approved external account requests.

alter table public.employees
  add column if not exists auth_user_id uuid unique,
  add column if not exists email text unique,
  add column if not exists identity_provider text,
  add column if not exists approval_status text not null default 'معتمد';

create table if not exists public.financial_transactions (
  id bigint generated by default as identity primary key,
  transaction_date date not null,
  transaction_type text not null check (transaction_type in ('إيراد', 'مصروف')),
  category text not null,
  amount numeric(14, 2) not null check (amount >= 0),
  description text,
  created_by bigint references public.employees(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.system_access_requests (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique,
  full_name text not null,
  email text not null unique,
  provider text not null check (provider in ('email', 'google', 'apple')),
  requested_role text not null,
  specialty text not null,
  status text not null default 'بانتظار الموافقة'
    check (status in ('بانتظار الموافقة', 'مقبول', 'مرفوض')),
  reviewed_by bigint references public.employees(id) on delete set null,
  review_note text,
  requested_at timestamptz not null default now(),
  reviewed_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists idx_financial_transactions_date
  on public.financial_transactions (transaction_date desc);
create index if not exists idx_financial_transactions_type
  on public.financial_transactions (transaction_type, transaction_date desc);
create index if not exists idx_access_requests_status
  on public.system_access_requests (status, requested_at desc);

drop trigger if exists set_system_access_requests_updated_at on public.system_access_requests;
create trigger set_system_access_requests_updated_at
  before update on public.system_access_requests
  for each row execute function public.set_updated_at();

alter table public.financial_transactions enable row level security;
alter table public.system_access_requests enable row level security;

revoke all on table public.financial_transactions, public.system_access_requests
  from anon, authenticated;
grant all on table public.financial_transactions, public.system_access_requests
  to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.app_schema_migrations (version)
values ('202608110003_reporting_and_access')
on conflict (version) do nothing;
