-- Real sign-in: the password is checked on the server against a bcrypt hash and
-- exchanged for a revocable session. Nothing secret reaches the browser bundle.

create extension if not exists pgcrypto;

-- Idempotent: the table is the credential store now, not a demo fixture.
do $$
begin
  if to_regclass('public.demo_login_accounts') is not null
     and to_regclass('public.login_accounts') is null then
    alter table public.demo_login_accounts rename to login_accounts;
  end if;
end;
$$;
alter table public.login_accounts add column if not exists must_change_password boolean not null default false;
alter table public.login_accounts add column if not exists last_login_at timestamptz;
alter table public.login_accounts add column if not exists failed_attempts integer not null default 0;
alter table public.login_accounts add column if not exists locked_until timestamptz;

-- Server-side sessions, so signing out and revoking an account take effect at once.
create table if not exists public.app_sessions (
  id bigint generated by default as identity primary key,
  token_hash text not null unique,
  employee_id bigint not null references public.employees(id) on delete cascade,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  expires_at timestamptz not null,
  user_agent text
);

create index if not exists idx_app_sessions_employee on public.app_sessions (employee_id);
create index if not exists idx_app_sessions_expiry on public.app_sessions (expires_at);

/**
 * Checks a password and opens a session in one step. Returns null on any
 * failure so a caller can never tell a wrong password from an unknown user.
 */
create or replace function public.open_session(
  p_login_name text,
  p_password text,
  p_token_hash text,
  p_user_agent text default null,
  p_days integer default 30
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  account public.login_accounts%rowtype;
  employee public.employees%rowtype;
begin
  select * into account from public.login_accounts
  where lower(login_name) = lower(trim(p_login_name));
  if not found then
    return null;
  end if;

  -- Five wrong tries buys a fifteen minute pause, which stops guessing without
  -- letting anyone lock a colleague out for long.
  if account.locked_until is not null and account.locked_until > now() then
    return jsonb_build_object('locked_until', account.locked_until);
  end if;

  if account.password_hash <> crypt(p_password, account.password_hash) then
    update public.login_accounts
    set failed_attempts = failed_attempts + 1,
        locked_until = case when failed_attempts + 1 >= 5 then now() + interval '15 minutes' else null end
    where id = account.id;
    return null;
  end if;

  select * into employee from public.employees where id = account.employee_id;
  if not found or employee.status <> 'نشط' or employee.approval_status <> 'معتمد' then
    return null;
  end if;

  update public.login_accounts
  set failed_attempts = 0, locked_until = null, last_login_at = now()
  where id = account.id;

  delete from public.app_sessions where expires_at < now();
  insert into public.app_sessions (token_hash, employee_id, expires_at, user_agent)
  values (p_token_hash, employee.id, now() + make_interval(days => greatest(1, p_days)), p_user_agent);

  return jsonb_build_object(
    'employee', jsonb_build_object(
      'id', employee.id,
      'full_name', employee.full_name,
      'role', employee.role,
      'specialty', employee.specialty,
      'username', account.login_name
    ),
    'must_change_password', account.must_change_password
  );
end;
$$;

/** Resolves a session cookie to its employee, refreshing the last-seen stamp. */
create or replace function public.resume_session(p_token_hash text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  employee public.employees%rowtype;
  account public.login_accounts%rowtype;
  session_id bigint;
begin
  select session.id into session_id
  from public.app_sessions session
  where session.token_hash = p_token_hash and session.expires_at > now();
  if session_id is null then
    return null;
  end if;

  select employees.* into employee
  from public.employees employees
  join public.app_sessions session on session.employee_id = employees.id
  where session.id = session_id;
  if employee.status <> 'نشط' or employee.approval_status <> 'معتمد' then
    delete from public.app_sessions where id = session_id;
    return null;
  end if;

  update public.app_sessions set last_seen_at = now() where id = session_id;
  select * into account from public.login_accounts where employee_id = employee.id;

  return jsonb_build_object(
    'id', employee.id,
    'full_name', employee.full_name,
    'role', employee.role,
    'specialty', employee.specialty,
    'username', coalesce(account.login_name, ''),
    'must_change_password', coalesce(account.must_change_password, false)
  );
end;
$$;

/** Changing a password ends every other session for that employee. */
create or replace function public.change_password(
  p_employee_id bigint,
  p_current_password text,
  p_new_password text,
  p_keep_token_hash text
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  account public.login_accounts%rowtype;
begin
  select * into account from public.login_accounts where employee_id = p_employee_id;
  if not found then
    return false;
  end if;
  if account.password_hash <> crypt(p_current_password, account.password_hash) then
    return false;
  end if;
  if length(coalesce(p_new_password, '')) < 8 then
    raise exception 'password too short';
  end if;

  update public.login_accounts
  set password_hash = crypt(p_new_password, gen_salt('bf', 12)),
      must_change_password = false,
      failed_attempts = 0,
      locked_until = null
  where id = account.id;

  delete from public.app_sessions
  where employee_id = p_employee_id and token_hash <> coalesce(p_keep_token_hash, '');
  return true;
end;
$$;

alter table public.app_sessions enable row level security;
alter table public.login_accounts enable row level security;
revoke all on table public.app_sessions, public.login_accounts from public, anon, authenticated;
grant all on table public.app_sessions, public.login_accounts to service_role;

revoke all on function public.open_session(text, text, text, text, integer) from public, anon, authenticated;
revoke all on function public.resume_session(text) from public, anon, authenticated;
revoke all on function public.change_password(bigint, text, text, text) from public, anon, authenticated;
grant execute on function public.open_session(text, text, text, text, integer) to service_role;
grant execute on function public.resume_session(text) to service_role;
grant execute on function public.change_password(bigint, text, text, text) to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.app_schema_migrations (version)
values ('202608110012_real_authentication')
on conflict (version) do nothing;
