-- Monthly duty roster for resident doctors: each resident declares the days they
-- can take a shift, the chief generates a balanced 12-hour morning/evening plan,
-- then publishes it to everyone.

create table if not exists public.shift_months (
  id bigint generated by default as identity primary key,
  month date not null unique,
  status text not null default 'مفتوح' check (status in ('مفتوح', 'قيد الجدولة', 'منشور')),
  doctors_per_shift integer not null default 1 check (doctors_per_shift between 1 and 6),
  morning_label text not null default 'صباحية',
  evening_label text not null default 'مسائية',
  morning_start text not null default '08:00',
  evening_start text not null default '20:00',
  shift_hours integer not null default 12 check (shift_hours between 4 and 24),
  notes text,
  published_at timestamptz,
  published_by bigint references public.employees(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shift_availability (
  id bigint generated by default as identity primary key,
  month_id bigint not null references public.shift_months(id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  available_days jsonb not null default '[]'::jsonb,
  preferred_shift text not null default 'كلاهما' check (preferred_shift in ('صباحية', 'مسائية', 'كلاهما')),
  max_shifts integer check (max_shifts is null or max_shifts >= 0),
  note text,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (month_id, employee_id)
);

create table if not exists public.shift_assignments (
  id bigint generated by default as identity primary key,
  month_id bigint not null references public.shift_months(id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  work_date date not null,
  shift text not null check (shift in ('صباحية', 'مسائية')),
  is_locked boolean not null default false,
  created_at timestamptz not null default now(),
  unique (work_date, shift, employee_id)
);

create index if not exists idx_shift_assignments_month on public.shift_assignments (month_id, work_date);
create index if not exists idx_shift_availability_month on public.shift_availability (month_id);

drop trigger if exists set_shift_months_updated_at on public.shift_months;
create trigger set_shift_months_updated_at
  before update on public.shift_months
  for each row execute function public.set_updated_at();

drop trigger if exists set_shift_availability_updated_at on public.shift_availability;
create trigger set_shift_availability_updated_at
  before update on public.shift_availability
  for each row execute function public.set_updated_at();

-- One readable row per assignment, so the dashboard, the bot and the WhatsApp
-- export all format the same data instead of re-joining it three ways.
create or replace view public.shift_schedule_overview as
select
  assignment.id,
  assignment.month_id,
  month.month,
  month.status,
  assignment.work_date,
  assignment.shift,
  assignment.is_locked,
  employee.id as employee_id,
  employee.full_name,
  employee.specialty
from public.shift_assignments assignment
join public.shift_months month on month.id = assignment.month_id
join public.employees employee on employee.id = assignment.employee_id;

alter table public.shift_months enable row level security;
alter table public.shift_availability enable row level security;
alter table public.shift_assignments enable row level security;

revoke all on table public.shift_months, public.shift_availability, public.shift_assignments
  from public, anon, authenticated;
grant all on table public.shift_months, public.shift_availability, public.shift_assignments
  to service_role;
revoke all on public.shift_schedule_overview from public, anon, authenticated;
grant select on public.shift_schedule_overview to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.app_schema_migrations (version)
values ('202608110010_resident_shift_schedules')
on conflict (version) do nothing;
