-- Staff presence, durable file metadata, operational tasks, and Telegram bot integration.
-- All runtime access remains server-side through the Supabase service role.

create table if not exists public.file_attachments (
  id bigint generated by default as identity primary key,
  bucket_name text not null,
  object_path text not null,
  entity_type text not null check (entity_type in ('patient', 'employee', 'doctor_call', 'task', 'report')),
  entity_id text not null,
  category text not null,
  original_filename text not null,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes > 0),
  checksum_sha256 text,
  uploaded_by bigint references public.employees(id) on delete set null,
  uploaded_by_name text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (bucket_name, object_path)
);

create table if not exists public.employee_attendance_sessions (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete restrict,
  clock_in_at timestamptz not null default now(),
  clock_out_at timestamptz,
  clock_in_source text not null default 'web'
    check (clock_in_source in ('web', 'telegram', 'admin', 'system')),
  clock_out_source text
    check (clock_out_source is null or clock_out_source in ('web', 'telegram', 'admin', 'system')),
  clock_in_note text,
  clock_out_note text,
  created_by bigint references public.employees(id) on delete set null,
  created_at timestamptz not null default now(),
  check (clock_out_at is null or clock_out_at >= clock_in_at)
);

create table if not exists public.employee_activity_events (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete cascade,
  employee_name text not null,
  employee_role text not null,
  activity_type text not null,
  entity_type text,
  entity_id text,
  description text not null,
  source text not null default 'web'
    check (source in ('web', 'telegram', 'admin', 'system')),
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create table if not exists public.operational_tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  assigned_employee_id bigint not null references public.employees(id) on delete restrict,
  related_patient_id bigint references public.patients(id) on delete set null,
  status text not null default 'مفتوحة'
    check (status in ('مفتوحة', 'قيد المتابعة', 'مكتملة', 'ملغاة')),
  priority text not null default 'اعتيادية'
    check (priority in ('اعتيادية', 'مهمة', 'عاجلة')),
  due_at timestamptz,
  created_by bigint references public.employees(id) on delete set null,
  completed_by bigint references public.employees(id) on delete set null,
  source text not null default 'web'
    check (source in ('web', 'telegram', 'admin', 'system')),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.telegram_accounts (
  id bigint generated by default as identity primary key,
  employee_id bigint not null unique references public.employees(id) on delete cascade,
  telegram_user_id bigint not null unique,
  chat_id bigint not null unique,
  username text,
  display_name text,
  status text not null default 'معتمد'
    check (status in ('بانتظار الموافقة', 'معتمد', 'محظور')),
  paired_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.telegram_link_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  employee_id bigint not null references public.employees(id) on delete cascade,
  created_by bigint references public.employees(id) on delete set null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now(),
  check (expires_at > created_at)
);

create table if not exists public.telegram_updates (
  update_id bigint primary key,
  chat_id bigint,
  employee_id bigint references public.employees(id) on delete set null,
  command text,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'مستلم'
    check (status in ('مستلم', 'تمت المعالجة', 'فشل')),
  error_message text,
  received_at timestamptz not null default now(),
  processed_at timestamptz
);

create unique index if not exists idx_attendance_one_open_session
  on public.employee_attendance_sessions (employee_id)
  where clock_out_at is null;
create index if not exists idx_attendance_clock_in
  on public.employee_attendance_sessions (clock_in_at desc);
create index if not exists idx_attendance_employee_history
  on public.employee_attendance_sessions (employee_id, clock_in_at desc);
create index if not exists idx_employee_activity_latest
  on public.employee_activity_events (employee_id, occurred_at desc);
create index if not exists idx_employee_activity_entity
  on public.employee_activity_events (entity_type, entity_id, occurred_at desc);
create index if not exists idx_operational_tasks_assignee
  on public.operational_tasks (assigned_employee_id, status, due_at);
create index if not exists idx_telegram_updates_received
  on public.telegram_updates (received_at desc);
create index if not exists idx_file_attachments_entity
  on public.file_attachments (entity_type, entity_id, created_at desc);

drop trigger if exists set_operational_tasks_updated_at on public.operational_tasks;
create trigger set_operational_tasks_updated_at
  before update on public.operational_tasks
  for each row execute function public.set_updated_at();

drop trigger if exists set_telegram_accounts_updated_at on public.telegram_accounts;
create trigger set_telegram_accounts_updated_at
  before update on public.telegram_accounts
  for each row execute function public.set_updated_at();

create or replace function public.record_attendance_event(
  p_employee_name text,
  p_action text,
  p_source text default 'web',
  p_note text default null,
  p_recorded_by_name text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  employee_record public.employees%rowtype;
  recorder_record public.employees%rowtype;
  session_record public.employee_attendance_sessions%rowtype;
  activity_description text;
begin
  if p_source not in ('web', 'telegram', 'admin', 'system') then
    raise exception 'Unsupported attendance source';
  end if;
  if p_action not in ('دخول', 'خروج') then
    raise exception 'Unsupported attendance action';
  end if;

  select * into employee_record
  from public.employees
  where full_name = trim(p_employee_name) and status = 'نشط'
  order by id limit 1;
  if employee_record.id is null then raise exception 'Employee not found'; end if;

  select * into recorder_record
  from public.employees
  where full_name = trim(coalesce(nullif(p_recorded_by_name, ''), p_employee_name)) and status = 'نشط'
  order by id limit 1;

  if p_action = 'دخول' then
    select * into session_record
    from public.employee_attendance_sessions
    where employee_id = employee_record.id and clock_out_at is null
    order by clock_in_at desc limit 1 for update;
    if session_record.id is not null then raise exception 'Employee already clocked in'; end if;

    insert into public.employee_attendance_sessions (
      employee_id, clock_in_source, clock_in_note, created_by
    ) values (
      employee_record.id, p_source, nullif(trim(p_note), ''), coalesce(recorder_record.id, employee_record.id)
    ) returning * into session_record;
    activity_description := 'سجّل الحضور إلى المستشفى';
  else
    select * into session_record
    from public.employee_attendance_sessions
    where employee_id = employee_record.id and clock_out_at is null
    order by clock_in_at desc limit 1 for update;
    if session_record.id is null then raise exception 'Employee is not clocked in'; end if;

    update public.employee_attendance_sessions set
      clock_out_at = now(),
      clock_out_source = p_source,
      clock_out_note = nullif(trim(p_note), '')
    where id = session_record.id
    returning * into session_record;
    activity_description := 'سجّل الانصراف من المستشفى';
  end if;

  insert into public.employee_activity_events (
    employee_id, employee_name, employee_role, activity_type, entity_type,
    entity_id, description, source, metadata
  ) values (
    employee_record.id, employee_record.full_name, employee_record.role,
    'حضور وانصراف', 'attendance_session', session_record.id::text,
    activity_description, p_source,
    jsonb_build_object('action', p_action, 'recordedBy', coalesce(recorder_record.full_name, employee_record.full_name))
  );

  insert into public.audit_logs (actor_id, action, entity_type, entity_id, after_data)
  values (
    coalesce(recorder_record.id, employee_record.id), 'تسجيل ' || p_action,
    'attendance_session', session_record.id::text,
    jsonb_build_object('employeeId', employee_record.id, 'employeeName', employee_record.full_name, 'source', p_source)
  );

  return jsonb_build_object(
    'id', session_record.id,
    'employeeId', employee_record.id,
    'employeeName', employee_record.full_name,
    'role', employee_record.role,
    'clockInAt', session_record.clock_in_at,
    'clockOutAt', session_record.clock_out_at,
    'isPresent', session_record.clock_out_at is null
  );
end;
$$;

create or replace function public.record_employee_activity(
  p_employee_name text,
  p_activity_type text,
  p_description text,
  p_entity_type text default null,
  p_entity_id text default null,
  p_source text default 'web',
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  employee_record public.employees%rowtype;
  activity_record public.employee_activity_events%rowtype;
begin
  if p_source not in ('web', 'telegram', 'admin', 'system') then
    raise exception 'Unsupported activity source';
  end if;
  select * into employee_record
  from public.employees
  where full_name = trim(p_employee_name) and status = 'نشط'
  order by id limit 1;
  if employee_record.id is null then raise exception 'Employee not found'; end if;

  insert into public.employee_activity_events (
    employee_id, employee_name, employee_role, activity_type,
    entity_type, entity_id, description, source, metadata
  ) values (
    employee_record.id, employee_record.full_name, employee_record.role,
    trim(p_activity_type), nullif(trim(p_entity_type), ''), nullif(trim(p_entity_id), ''),
    trim(p_description), p_source, coalesce(p_metadata, '{}'::jsonb)
  ) returning * into activity_record;

  return jsonb_build_object('id', activity_record.id, 'occurredAt', activity_record.occurred_at);
end;
$$;

create or replace view public.employee_presence_overview
with (security_invoker = true)
as
select
  employee.id as employee_id,
  employee.full_name,
  employee.role,
  employee.specialty,
  employee.status as employee_status,
  (open_session.id is not null) as is_present,
  open_session.id as attendance_session_id,
  open_session.clock_in_at,
  open_session.clock_in_source,
  open_session.clock_in_note,
  last_activity.activity_type as last_activity_type,
  last_activity.description as last_activity,
  last_activity.source as last_activity_source,
  last_activity.occurred_at as last_activity_at,
  telegram.status as telegram_status,
  telegram.username as telegram_username,
  telegram.last_seen_at as telegram_last_seen_at
from public.employees employee
left join lateral (
  select attendance.*
  from public.employee_attendance_sessions attendance
  where attendance.employee_id = employee.id and attendance.clock_out_at is null
  order by attendance.clock_in_at desc
  limit 1
) open_session on true
left join lateral (
  select activity.activity_type, activity.description, activity.source, activity.occurred_at
  from public.employee_activity_events activity
  where activity.employee_id = employee.id
  order by activity.occurred_at desc
  limit 1
) last_activity on true
left join public.telegram_accounts telegram on telegram.employee_id = employee.id
where employee.status = 'نشط';

do $$
begin
  if exists (select 1 from pg_namespace where nspname = 'storage') then
    insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
    values
      ('patient-files', 'patient-files', false, 15728640,
        array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif', 'application/pdf']),
      ('employee-files', 'employee-files', false, 10485760,
        array['image/jpeg', 'image/png', 'image/webp', 'application/pdf']),
      ('system-exports', 'system-exports', false, 26214400,
        array['application/pdf', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'text/csv'])
    on conflict (id) do update
    set public = false,
        file_size_limit = excluded.file_size_limit,
        allowed_mime_types = excluded.allowed_mime_types;
  end if;
end $$;

alter table public.file_attachments enable row level security;
alter table public.employee_attendance_sessions enable row level security;
alter table public.employee_activity_events enable row level security;
alter table public.operational_tasks enable row level security;
alter table public.telegram_accounts enable row level security;
alter table public.telegram_link_codes enable row level security;
alter table public.telegram_updates enable row level security;

revoke all on table
  public.file_attachments,
  public.employee_attendance_sessions,
  public.employee_activity_events,
  public.operational_tasks,
  public.telegram_accounts,
  public.telegram_link_codes,
  public.telegram_updates
from anon, authenticated;
grant all on table
  public.file_attachments,
  public.employee_attendance_sessions,
  public.employee_activity_events,
  public.operational_tasks,
  public.telegram_accounts,
  public.telegram_link_codes,
  public.telegram_updates
to service_role;
revoke all on public.employee_presence_overview from public, anon, authenticated;
grant select on public.employee_presence_overview to service_role;

revoke all on function public.record_attendance_event(text, text, text, text, text) from public, anon, authenticated;
grant execute on function public.record_attendance_event(text, text, text, text, text) to service_role;
revoke all on function public.record_employee_activity(text, text, text, text, text, text, jsonb) from public, anon, authenticated;
grant execute on function public.record_employee_activity(text, text, text, text, text, text, jsonb) to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.app_schema_migrations (version)
values ('202608110005_staff_presence_files_and_telegram')
on conflict (version) do nothing;
