-- Verified Telegram bot administrators and approval queue for unknown /start senders.

alter table public.telegram_accounts
  add column if not exists is_bot_admin boolean not null default false;

create table if not exists public.telegram_bot_admin_allowlist (
  id bigint generated by default as identity primary key,
  employee_id bigint not null unique references public.employees(id) on delete cascade,
  telegram_username text not null,
  phone_number text not null,
  status text not null default 'بانتظار التحقق'
    check (status in ('بانتظار التحقق', 'تم التحقق', 'ملغى')),
  telegram_user_id bigint unique,
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.telegram_bot_admin_requests (
  id bigint generated by default as identity primary key,
  telegram_user_id bigint not null unique,
  chat_id bigint not null,
  username text,
  display_name text,
  status text not null default 'بانتظار الموافقة'
    check (status in ('بانتظار الموافقة', 'مقبول', 'مرفوض')),
  reviewed_by bigint references public.employees(id) on delete set null,
  reviewed_at timestamptz,
  requested_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_telegram_admin_allowlist_username
  on public.telegram_bot_admin_allowlist (lower(telegram_username));
create index if not exists idx_telegram_admin_requests_status
  on public.telegram_bot_admin_requests (status, requested_at desc);

drop trigger if exists set_telegram_bot_admin_allowlist_updated_at on public.telegram_bot_admin_allowlist;
create trigger set_telegram_bot_admin_allowlist_updated_at
  before update on public.telegram_bot_admin_allowlist
  for each row execute function public.set_updated_at();

drop trigger if exists set_telegram_bot_admin_requests_updated_at on public.telegram_bot_admin_requests;
create trigger set_telegram_bot_admin_requests_updated_at
  before update on public.telegram_bot_admin_requests
  for each row execute function public.set_updated_at();

insert into public.employees (
  full_name, employee_number, username, phone, role, specialty,
  join_date, status, approval_status
)
values (
  'د. مصطفى البياتي', 'BOT-ADMIN-001', 'bot.dr_mustafa_albayati',
  '+964 770 569 3132', 'الإدارة العليا', 'إدارة بوت البياتي',
  current_date, 'نشط', 'معتمد'
)
on conflict (employee_number) do update
set full_name = excluded.full_name,
    username = excluded.username,
    phone = excluded.phone,
    role = excluded.role,
    specialty = excluded.specialty,
    status = excluded.status,
    approval_status = excluded.approval_status,
    updated_at = now();

insert into public.telegram_bot_admin_allowlist (
  employee_id, telegram_username, phone_number, status
)
select id, 'dr_mustafa_albayati', '+9647705693132', 'بانتظار التحقق'
from public.employees
where employee_number = 'BOT-ADMIN-001'
on conflict (employee_id) do update
set telegram_username = excluded.telegram_username,
    phone_number = excluded.phone_number,
    status = case
      when public.telegram_bot_admin_allowlist.status = 'تم التحقق' then 'تم التحقق'
      else 'بانتظار التحقق'
    end,
    updated_at = now();

alter table public.telegram_bot_admin_allowlist enable row level security;
alter table public.telegram_bot_admin_requests enable row level security;

revoke all on table
  public.telegram_bot_admin_allowlist,
  public.telegram_bot_admin_requests
from anon, authenticated;
grant all on table
  public.telegram_bot_admin_allowlist,
  public.telegram_bot_admin_requests
to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.app_schema_migrations (version)
values ('202608110006_telegram_admins_and_button_menu')
on conflict (version) do nothing;
