-- Clean preview baseline: keep the schema, reset operational records, seed only approved demo identities.

create table if not exists public.demo_login_accounts (
  id bigint generated by default as identity primary key,
  employee_id bigint not null unique references public.employees(id) on delete cascade,
  login_name text not null unique,
  password_hash text not null,
  is_demo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.telegram_bot_admin_allowlist
  alter column telegram_username drop not null;

truncate table
  public.telegram_updates,
  public.telegram_link_codes,
  public.telegram_accounts,
  public.telegram_bot_admin_requests,
  public.telegram_bot_admin_allowlist,
  public.employee_activity_events,
  public.employee_attendance_sessions,
  public.operational_tasks,
  public.file_attachments,
  public.doctor_call_objections,
  public.doctor_call_deliveries,
  public.doctor_call_revisions,
  public.doctor_call_consultations,
  public.call_details,
  public.doctor_calls,
  public.handover_patients,
  public.doctor_shift_handovers,
  public.inpatient_payments,
  public.patient_events,
  public.procedures,
  public.financial_transactions,
  public.system_access_requests,
  public.audit_logs,
  public.doctor_caps,
  public.patients,
  public.demo_login_accounts,
  public.employees
restart identity cascade;

insert into public.employees (
  full_name, employee_number, username, phone, role, specialty,
  join_date, max_consultations, daily_cap, status, approval_status
)
values
  ('مصطفى البياتي', 'DEMO-ADMIN-001', 'mustafa', '+964 770 569 3132', 'الإدارة العليا', 'رئاسة القسم', current_date, null, null, 'نشط', 'معتمد'),
  ('د. شهد', 'DEMO-DOC-001', 'shahd', null, 'طبيب مقيم', 'الردهة والرقود', current_date, 0, 0, 'نشط', 'معتمد'),
  ('د. تبارك', 'DEMO-DOC-002', 'tabarak', null, 'طبيب مقيم', 'الاستشارية', current_date, 0, 0, 'نشط', 'معتمد'),
  ('د. فنار', 'DEMO-DOC-003', 'fanar', null, 'طبيب مقيم', 'صالة الولادة', current_date, 0, 0, 'نشط', 'معتمد'),
  ('Admin', 'DEMO-DEV-001', 'Admin', null, 'مطور النظام', 'إدارة النظام ومعاينة الحسابات', current_date, null, null, 'نشط', 'معتمد'),
  ('مدير بوت معتمد', 'BOT-ADMIN-002', 'bot.admin.07884669922', '+964 788 466 9922', 'مدير بوت', 'إدارة بوت البياتي', current_date, null, null, 'نشط', 'معتمد');

insert into public.doctor_caps (doctor_id, max_consultations, max_daily_amount)
select id, 0, 0
from public.employees
where role = 'طبيب مقيم';

insert into public.demo_login_accounts (employee_id, login_name, password_hash)
select employee.id, credentials.login_name, crypt(credentials.password, gen_salt('bf', 12))
from (values
  ('DEMO-ADMIN-001', 'mustafa', 'Mustafa123'),
  ('DEMO-DOC-001', 'shahd', 'Shahd123'),
  ('DEMO-DOC-002', 'tabarak', 'Tabarak123'),
  ('DEMO-DOC-003', 'fanar', 'Fanar123'),
  ('DEMO-DEV-001', 'Admin', 'Ahmed123')
) as credentials(employee_number, login_name, password)
join public.employees employee on employee.employee_number = credentials.employee_number;

insert into public.telegram_bot_admin_allowlist (
  employee_id, telegram_username, phone_number, status
)
select id, 'dr_mustafa_albayati', '+9647705693132', 'بانتظار التحقق'
from public.employees
where employee_number = 'DEMO-ADMIN-001'
union all
select id, null, '+9647884669922', 'بانتظار التحقق'
from public.employees
where employee_number = 'BOT-ADMIN-002';

drop trigger if exists set_demo_login_accounts_updated_at on public.demo_login_accounts;
create trigger set_demo_login_accounts_updated_at
  before update on public.demo_login_accounts
  for each row execute function public.set_updated_at();

alter table public.demo_login_accounts enable row level security;
revoke all on table public.demo_login_accounts from anon, authenticated;
grant all on table public.demo_login_accounts to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.app_schema_migrations (version)
values ('202608110007_clean_demo_seed_and_authorized_bot_admins')
on conflict (version) do nothing;
