-- Al-Bayati Hospital: production PostgreSQL schema
-- Safe to run more than once. Runtime access is restricted to the server-side service role.

create extension if not exists pgcrypto;

create table if not exists public.app_schema_migrations (
  version text primary key,
  applied_at timestamptz not null default now()
);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  full_name text not null,
  employee_number text not null unique,
  username text not null unique,
  phone text,
  role text not null,
  specialty text not null,
  join_date date not null,
  max_consultations integer check (max_consultations is null or max_consultations >= 0),
  daily_cap numeric(14, 2) check (daily_cap is null or daily_cap >= 0),
  status text not null default 'نشط',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.patients (
  id bigint generated by default as identity primary key,
  full_name text not null,
  file_number text not null unique,
  birth_date date,
  gender text not null,
  phone text,
  admission_date date not null,
  department text not null,
  attending_doctor text,
  payment_category text not null default 'نقدي',
  entry_type text not null default 'استشارية',
  patient_status text not null default 'نشط',
  billing_mode text not null default 'مقطوعي',
  is_newborn boolean not null default false,
  mother_id bigint references public.patients(id) on delete restrict,
  twin_order integer check (twin_order is null or twin_order > 0),
  discharge_date date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((is_newborn = false and mother_id is null) or (is_newborn = true and mother_id is not null))
);

create table if not exists public.patient_events (
  id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id) on delete restrict,
  event_type text not null,
  amount numeric(14, 2) not null default 0 check (amount >= 0),
  is_invalidated boolean not null default false,
  invalidated_reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.procedures (
  id bigint generated by default as identity primary key,
  name text not null unique,
  base_price numeric(14, 2) not null default 0 check (base_price >= 0),
  category text not null default 'خاضع للسقف',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.doctor_calls (
  id bigint generated by default as identity primary key,
  doctor_id bigint not null references public.employees(id) on delete restrict,
  call_date date not null,
  status text not null default 'قيد الإدخال',
  total_calculated numeric(14, 2) not null default 0 check (total_calculated >= 0),
  total_approved numeric(14, 2) not null default 0 check (total_approved >= 0),
  submitted_at timestamptz,
  approved_at timestamptz,
  approved_by bigint references public.employees(id) on delete restrict,
  review_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (doctor_id, call_date)
);

create table if not exists public.call_details (
  id bigint generated by default as identity primary key,
  call_id bigint not null references public.doctor_calls(id) on delete cascade,
  patient_id bigint not null references public.patients(id) on delete restrict,
  procedure_id bigint not null references public.procedures(id) on delete restrict,
  quantity integer not null default 1 check (quantity > 0),
  amount numeric(14, 2) not null check (amount >= 0),
  attachment_url text,
  is_invalidated boolean not null default false,
  invalidated_reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.inpatient_payments (
  id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id) on delete restrict,
  record_date date not null,
  payment_status text not null default 'ليس بعد',
  updated_by bigint references public.employees(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (patient_id, record_date)
);

create table if not exists public.doctor_caps (
  id bigint generated by default as identity primary key,
  doctor_id bigint not null unique references public.employees(id) on delete cascade,
  max_consultations integer not null default 10 check (max_consultations >= 0),
  max_daily_amount numeric(14, 2) not null default 200000 check (max_daily_amount >= 0),
  updated_by bigint references public.employees(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id bigint references public.employees(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_employees_created_at on public.employees (created_at desc);
create index if not exists idx_employees_role on public.employees (role);
create index if not exists idx_patients_created_at on public.patients (created_at desc);
create index if not exists idx_patients_mother_id on public.patients (mother_id);
create index if not exists idx_patients_status on public.patients (patient_status);
create index if not exists idx_patient_events_patient_id on public.patient_events (patient_id);
create index if not exists idx_patient_events_created_at on public.patient_events (created_at desc);
create index if not exists idx_doctor_calls_date on public.doctor_calls (call_date desc);
create index if not exists idx_call_details_call_id on public.call_details (call_id);
create index if not exists idx_call_details_patient_id on public.call_details (patient_id);
create index if not exists idx_inpatient_payments_date on public.inpatient_payments (record_date desc);
create index if not exists idx_audit_logs_entity on public.audit_logs (entity_type, entity_id);

insert into public.procedures (name, base_price, category)
values
  ('استشارية', 10000, 'خاضع لسقف الاستشاريات'),
  ('ولادة طبيعية', 10000, 'خاضع للسقف اليومي'),
  ('عملية قيصرية', 60000, 'خاضع للسقف اليومي'),
  ('رقود', 0, 'تراكمي حسب الأيام المدفوعة')
on conflict (name) do update
set base_price = excluded.base_price,
    category = excluded.category,
    updated_at = now();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array['employees', 'patients', 'procedures', 'doctor_calls', 'inpatient_payments', 'doctor_caps']
  loop
    execute format('drop trigger if exists set_%I_updated_at on public.%I', table_name, table_name);
    execute format('create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()', table_name, table_name);
  end loop;
end;
$$;

create or replace function public.register_patient(
  p_full_name text,
  p_file_number text,
  p_birth_date date,
  p_gender text,
  p_phone text,
  p_admission_date date,
  p_department text,
  p_attending_doctor text,
  p_payment_category text,
  p_entry_type text,
  p_billing_mode text,
  p_notes text,
  p_initial_price numeric,
  p_newborn_names jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  mother public.patients%rowtype;
  newborn_name text;
  newborn_index bigint;
  newborn_total integer := jsonb_array_length(coalesce(p_newborn_names, '[]'::jsonb));
begin
  insert into public.patients (
    full_name, file_number, birth_date, gender, phone, admission_date,
    department, attending_doctor, payment_category, entry_type, billing_mode, notes
  ) values (
    trim(p_full_name), trim(p_file_number), p_birth_date, trim(p_gender), nullif(trim(p_phone), ''),
    p_admission_date, trim(p_department), nullif(trim(p_attending_doctor), ''),
    coalesce(nullif(trim(p_payment_category), ''), 'نقدي'),
    coalesce(nullif(trim(p_entry_type), ''), 'استشارية'),
    coalesce(nullif(trim(p_billing_mode), ''), 'مقطوعي'), nullif(trim(p_notes), '')
  ) returning * into mother;

  for newborn_name, newborn_index in
    select value, ordinality
    from jsonb_array_elements_text(coalesce(p_newborn_names, '[]'::jsonb)) with ordinality
  loop
    insert into public.patients (
      full_name, file_number, gender, admission_date, department, attending_doctor,
      payment_category, entry_type, billing_mode, is_newborn, mother_id, twin_order
    ) values (
      newborn_name, p_file_number || '-N' || newborn_index, 'غير محدد', p_admission_date,
      'حديثو الولادة', nullif(trim(p_attending_doctor), ''),
      coalesce(nullif(trim(p_payment_category), ''), 'نقدي'), 'مولود جديد',
      'مرتبط بملف الأم', true, mother.id,
      case when newborn_total > 1 then newborn_index::integer else null end
    );
  end loop;

  insert into public.patient_events (patient_id, event_type, amount)
  values (mother.id, p_entry_type, greatest(coalesce(p_initial_price, 0), 0));

  insert into public.audit_logs (action, entity_type, entity_id, after_data)
  values ('register', 'patient', mother.id::text, to_jsonb(mother));

  return jsonb_build_object(
    'record', to_jsonb(mother) || jsonb_build_object('newborn_count', newborn_total),
    'newborn_names', coalesce(p_newborn_names, '[]'::jsonb)
  );
end;
$$;

create or replace function public.transition_patient_lifecycle(
  p_patient_id bigint,
  p_action text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  patient_record public.patients%rowtype;
  result_message text;
begin
  if p_action = 'convert_to_inpatient' then
    update public.patient_events
    set is_invalidated = true,
        invalidated_reason = 'تم التحول إلى رقود'
    where patient_id = p_patient_id
      and event_type in ('ولادة طبيعية', 'عملية قيصرية')
      and is_invalidated = false;

    update public.call_details details
    set is_invalidated = true,
        invalidated_reason = 'تم التحول إلى رقود'
    from public.procedures procedures
    where details.patient_id = p_patient_id
      and details.procedure_id = procedures.id
      and procedures.name in ('ولادة طبيعية', 'عملية قيصرية')
      and details.is_invalidated = false;

    update public.patients
    set entry_type = 'رقود', billing_mode = 'تراكمي'
    where id = p_patient_id
    returning * into patient_record;

    if patient_record.id is null then
      raise exception 'Patient not found';
    end if;

    insert into public.patient_events (patient_id, event_type, amount)
    values (p_patient_id, 'رقود', 0);
    result_message := 'أُلغيت تسعيرة الولادة وبدأ احتساب الرقود التراكمي';
  elsif p_action = 'discharge' then
    update public.patients
    set patient_status = 'خرجت', discharge_date = current_date
    where id = p_patient_id
    returning * into patient_record;

    if patient_record.id is null then
      raise exception 'Patient not found';
    end if;

    insert into public.patient_events (patient_id, event_type, amount)
    values (p_patient_id, 'خروج المريضة', 0);
    result_message := 'أُغلق الملف بعد المراجعة النهائية';
  else
    raise exception 'Unsupported lifecycle action';
  end if;

  insert into public.audit_logs (action, entity_type, entity_id, after_data)
  values (p_action, 'patient', p_patient_id::text, to_jsonb(patient_record));

  return jsonb_build_object('patient', to_jsonb(patient_record), 'message', result_message);
end;
$$;

alter table public.employees enable row level security;
alter table public.patients enable row level security;
alter table public.patient_events enable row level security;
alter table public.procedures enable row level security;
alter table public.doctor_calls enable row level security;
alter table public.call_details enable row level security;
alter table public.inpatient_payments enable row level security;
alter table public.doctor_caps enable row level security;
alter table public.audit_logs enable row level security;

revoke all on table public.employees, public.patients, public.patient_events, public.procedures,
  public.doctor_calls, public.call_details, public.inpatient_payments, public.doctor_caps, public.audit_logs
  from anon, authenticated;
grant all on table public.employees, public.patients, public.patient_events, public.procedures,
  public.doctor_calls, public.call_details, public.inpatient_payments, public.doctor_caps, public.audit_logs
  to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke all on function public.register_patient(text, text, date, text, text, date, text, text, text, text, text, text, numeric, jsonb) from public, anon, authenticated;
revoke all on function public.transition_patient_lifecycle(bigint, text) from public, anon, authenticated;
grant execute on function public.register_patient(text, text, date, text, text, date, text, text, text, text, text, text, numeric, jsonb) to service_role;
grant execute on function public.transition_patient_lifecycle(bigint, text) to service_role;

insert into public.app_schema_migrations (version)
values ('202608110001_initial_hospital_schema')
on conflict (version) do nothing;
