-- Resident work logs, immutable edit history, delivery tracking, and doctor objections.
-- Financial policy: consultations/births/cesareans are calculated immediately.
-- Inpatient compensation remains pending until Accounts confirms paid inpatient days.

alter table public.doctor_calls
  add column if not exists call_hours integer not null default 12
    check (call_hours in (12, 24)),
  add column if not exists inpatient_count integer not null default 0
    check (inpatient_count >= 0),
  add column if not exists consultation_count integer not null default 0
    check (consultation_count >= 0),
  add column if not exists natural_birth_count integer not null default 0
    check (natural_birth_count >= 0),
  add column if not exists cesarean_count integer not null default 0
    check (cesarean_count >= 0),
  add column if not exists special_cases_count integer not null default 0
    check (special_cases_count >= 0),
  add column if not exists special_cases_note text,
  add column if not exists last_edited_by bigint references public.employees(id) on delete set null,
  add column if not exists last_edited_by_name text;

create table if not exists public.doctor_call_consultations (
  id bigint generated by default as identity primary key,
  call_id bigint not null references public.doctor_calls(id) on delete cascade,
  case_number integer not null check (case_number > 0),
  case_label text,
  evidence_path text not null,
  amount numeric(14, 2) not null default 10000 check (amount >= 0),
  created_by bigint references public.employees(id) on delete set null,
  created_by_name text not null,
  created_at timestamptz not null default now(),
  unique (call_id, case_number)
);

create table if not exists public.doctor_call_revisions (
  id bigint generated by default as identity primary key,
  call_id bigint not null references public.doctor_calls(id) on delete cascade,
  editor_id bigint references public.employees(id) on delete set null,
  editor_name text not null,
  action text not null check (action in ('إنشاء', 'تعديل', 'تسوية اعتراض')),
  before_data jsonb,
  after_data jsonb not null,
  financial_delta numeric(14, 2) not null default 0,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.doctor_call_deliveries (
  id bigint generated by default as identity primary key,
  call_id bigint not null references public.doctor_calls(id) on delete cascade,
  recipient_role text not null check (recipient_role in ('الحسابات', 'رئيس المقيمين', 'الإدارة العليا')),
  status text not null default 'تم الإرسال' check (status in ('تم الإرسال', 'تم الاطلاع')),
  sent_at timestamptz not null default now(),
  viewed_at timestamptz,
  unique (call_id, recipient_role)
);

create table if not exists public.doctor_call_objections (
  id bigint generated by default as identity primary key,
  call_id bigint not null references public.doctor_calls(id) on delete cascade,
  doctor_id bigint not null references public.employees(id) on delete restrict,
  doctor_name text not null,
  reason text not null,
  disputed_amount numeric(14, 2) not null check (disputed_amount > 0),
  status text not null default 'مرسل'
    check (status in ('مرسل', 'قيد التدقيق', 'تم التدقيق', 'مرفوض')),
  reviewer_id bigint references public.employees(id) on delete set null,
  reviewer_name text,
  response_note text,
  adjustment_amount numeric(14, 2) not null default 0,
  submitted_at timestamptz not null default now(),
  resolved_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists idx_call_consultations_call
  on public.doctor_call_consultations (call_id, case_number);
create index if not exists idx_call_revisions_call
  on public.doctor_call_revisions (call_id, created_at desc);
create index if not exists idx_call_deliveries_recipient
  on public.doctor_call_deliveries (recipient_role, status, sent_at desc);
create index if not exists idx_call_objections_status
  on public.doctor_call_objections (status, submitted_at desc);
create index if not exists idx_doctor_calls_last_editor
  on public.doctor_calls (last_edited_by_name, updated_at desc);

drop trigger if exists set_doctor_call_objections_updated_at on public.doctor_call_objections;
create trigger set_doctor_call_objections_updated_at
  before update on public.doctor_call_objections
  for each row execute function public.set_updated_at();

insert into public.employees
  (full_name, employee_number, username, role, specialty, join_date, max_consultations, daily_cap, status, approval_status)
values
  ('د. أحمد البياتي', 'DEMO-DOC-001', 'doctor.ahmed', 'طبيب مقيم', 'النسائية والتوليد', current_date, 10, 200000, 'نشط', 'معتمد'),
  ('د. فنار', 'DEMO-DOC-002', 'doctor.fanar', 'طبيب مقيم', 'النسائية والتوليد', current_date, 10, 200000, 'نشط', 'معتمد'),
  ('د. تبارك', 'DEMO-DOC-003', 'doctor.tabarak', 'طبيب مقيم', 'النسائية والتوليد', current_date, 10, 200000, 'نشط', 'معتمد'),
  ('د. شهد', 'DEMO-DOC-004', 'doctor.shahd', 'طبيب مقيم', 'النسائية والتوليد', current_date, 10, 200000, 'نشط', 'معتمد'),
  ('سلمى نزار', 'DEMO-ACC-001', 'accounts.salma', 'الحسابات', 'الحسابات', current_date, null, null, 'نشط', 'معتمد'),
  ('زهراء علي', 'DEMO-ACC-002', 'accounts.zahraa', 'الحسابات', 'الحسابات', current_date, null, null, 'نشط', 'معتمد'),
  ('د. ليلى قاسم', 'DEMO-CHIEF-001', 'chief.layla', 'رئيس المقيمين', 'النسائية والتوليد', current_date, 10, 200000, 'نشط', 'معتمد'),
  ('رئاسة القسم', 'DEMO-ADMIN-001', 'department.head', 'الإدارة العليا', 'إدارة القسم', current_date, null, null, 'نشط', 'معتمد'),
  ('مطور النظام', 'DEMO-DEV-001', 'system.developer', 'مطور النظام', 'تطوير النظام', current_date, null, null, 'نشط', 'معتمد')
on conflict (employee_number) do update
set full_name = excluded.full_name,
    role = excluded.role,
    specialty = excluded.specialty,
    max_consultations = excluded.max_consultations,
    daily_cap = excluded.daily_cap,
    status = excluded.status,
    approval_status = excluded.approval_status,
    updated_at = now();

insert into public.doctor_caps (doctor_id, max_consultations, max_daily_amount)
select id, coalesce(max_consultations, 10), coalesce(daily_cap, 200000)
from public.employees
where role = 'طبيب مقيم'
on conflict (doctor_id) do nothing;

create or replace function public.save_resident_work_log(
  p_doctor_name text,
  p_editor_name text,
  p_call_date date,
  p_call_hours integer,
  p_inpatient_count integer,
  p_consultation_count integer,
  p_birth_count integer,
  p_cesarean_count integer,
  p_special_count integer,
  p_special_note text,
  p_evidence jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  doctor_record public.employees%rowtype;
  editor_record public.employees%rowtype;
  call_record public.doctor_calls%rowtype;
  previous_snapshot jsonb;
  next_snapshot jsonb;
  old_approved numeric(14, 2) := 0;
  entered_total numeric(14, 2);
  approved_total numeric(14, 2);
  max_consultations integer := 10;
  combined_cap numeric(14, 2) := 200000;
  evidence_count integer;
  evidence_item jsonb;
  action_name text := 'إنشاء';
begin
  if p_call_hours not in (12, 24) then
    raise exception 'ساعات الكول يجب أن تكون 12 أو 24';
  end if;
  if least(p_inpatient_count, p_consultation_count, p_birth_count, p_cesarean_count, p_special_count) < 0 then
    raise exception 'أعداد الحالات لا يمكن أن تكون سالبة';
  end if;

  select * into doctor_record from public.employees
  where full_name = trim(p_doctor_name) and role = 'طبيب مقيم' and status = 'نشط'
  order by id limit 1;
  if doctor_record.id is null then
    raise exception 'حساب الطبيب المقيم غير موجود';
  end if;

  select * into editor_record from public.employees
  where full_name = trim(p_editor_name) and status = 'نشط'
  order by id limit 1;
  if editor_record.id is null then
    raise exception 'حساب منفذ التعديل غير موجود';
  end if;

  evidence_count := jsonb_array_length(coalesce(p_evidence, '[]'::jsonb));
  if evidence_count <> p_consultation_count then
    raise exception 'يجب إرفاق صورة واحدة لكل حالة استشارية';
  end if;

  select coalesce(dc.max_consultations, doctor_record.max_consultations, 10),
         coalesce(dc.max_daily_amount, doctor_record.daily_cap, 200000)
  into max_consultations, combined_cap
  from (select 1) seed
  left join public.doctor_caps dc on dc.doctor_id = doctor_record.id;

  entered_total := p_consultation_count * 10000
    + p_birth_count * 80000
    + p_cesarean_count * 120000;
  approved_total := least(p_consultation_count, max_consultations) * 10000
    + least(p_birth_count * 80000 + p_cesarean_count * 120000, combined_cap);

  select * into call_record from public.doctor_calls
  where doctor_id = doctor_record.id and call_date = p_call_date
  for update;

  if call_record.id is not null then
    action_name := 'تعديل';
    old_approved := call_record.total_approved;
    previous_snapshot := jsonb_build_object(
      'callHours', call_record.call_hours,
      'inpatients', call_record.inpatient_count,
      'consultations', call_record.consultation_count,
      'births', call_record.natural_birth_count,
      'cesareans', call_record.cesarean_count,
      'specialCases', call_record.special_cases_count,
      'specialNote', call_record.special_cases_note,
      'totalCalculated', call_record.total_calculated,
      'totalApproved', call_record.total_approved
    );
    update public.doctor_calls set
      call_hours = p_call_hours,
      inpatient_count = p_inpatient_count,
      consultation_count = p_consultation_count,
      natural_birth_count = p_birth_count,
      cesarean_count = p_cesarean_count,
      special_cases_count = p_special_count,
      special_cases_note = nullif(trim(p_special_note), ''),
      status = 'مرسل للتدقيق',
      total_calculated = entered_total,
      total_approved = approved_total,
      submitted_at = now(),
      approved_at = null,
      approved_by = null,
      last_edited_by = editor_record.id,
      last_edited_by_name = editor_record.full_name,
      updated_at = now()
    where id = call_record.id
    returning * into call_record;
  else
    insert into public.doctor_calls (
      doctor_id, call_date, call_hours, inpatient_count, consultation_count,
      natural_birth_count, cesarean_count, special_cases_count, special_cases_note,
      status, total_calculated, total_approved, submitted_at,
      last_edited_by, last_edited_by_name
    ) values (
      doctor_record.id, p_call_date, p_call_hours, p_inpatient_count, p_consultation_count,
      p_birth_count, p_cesarean_count, p_special_count, nullif(trim(p_special_note), ''),
      'مرسل للتدقيق', entered_total, approved_total, now(),
      editor_record.id, editor_record.full_name
    ) returning * into call_record;
  end if;

  delete from public.doctor_call_consultations where call_id = call_record.id;
  for evidence_item in select value from jsonb_array_elements(coalesce(p_evidence, '[]'::jsonb))
  loop
    insert into public.doctor_call_consultations (
      call_id, case_number, case_label, evidence_path, amount, created_by, created_by_name
    ) values (
      call_record.id,
      (evidence_item ->> 'caseNumber')::integer,
      nullif(trim(evidence_item ->> 'caseLabel'), ''),
      evidence_item ->> 'path',
      10000,
      editor_record.id,
      editor_record.full_name
    );
  end loop;

  next_snapshot := jsonb_build_object(
    'callHours', p_call_hours,
    'inpatients', p_inpatient_count,
    'consultations', p_consultation_count,
    'births', p_birth_count,
    'cesareans', p_cesarean_count,
    'specialCases', p_special_count,
    'specialNote', nullif(trim(p_special_note), ''),
    'totalCalculated', entered_total,
    'totalApproved', approved_total,
    'inpatientFinancialStatus', 'بانتظار تأكيد الحسابات'
  );

  insert into public.doctor_call_revisions (
    call_id, editor_id, editor_name, action, before_data, after_data, financial_delta, note
  ) values (
    call_record.id, editor_record.id, editor_record.full_name, action_name,
    previous_snapshot, next_snapshot, approved_total - old_approved,
    case when action_name = 'إنشاء' then 'إرسال سجل المناوبة للمراجعة' else 'تعديل سجل مناوبة قائم وإعادة إرساله' end
  );

  insert into public.doctor_call_deliveries (call_id, recipient_role, status, sent_at, viewed_at)
  values
    (call_record.id, 'الحسابات', 'تم الإرسال', now(), null),
    (call_record.id, 'رئيس المقيمين', 'تم الإرسال', now(), null),
    (call_record.id, 'الإدارة العليا', 'تم الإرسال', now(), null)
  on conflict (call_id, recipient_role) do update
  set status = 'تم الإرسال', sent_at = now(), viewed_at = null;

  insert into public.audit_logs (actor_id, action, entity_type, entity_id, before_data, after_data)
  values (editor_record.id, action_name || ' سجل مناوبة', 'doctor_call', call_record.id::text, previous_snapshot, next_snapshot);

  return jsonb_build_object(
    'id', call_record.id,
    'doctorName', doctor_record.full_name,
    'editorName', editor_record.full_name,
    'status', call_record.status,
    'totalCalculated', entered_total,
    'totalApproved', approved_total,
    'financialDelta', approved_total - old_approved
  );
end;
$$;

create or replace function public.resolve_doctor_call_objection(
  p_objection_id bigint,
  p_reviewer_name text,
  p_decision text,
  p_response_note text,
  p_adjustment_amount numeric default 0
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  objection_record public.doctor_call_objections%rowtype;
  reviewer_record public.employees%rowtype;
  call_record public.doctor_calls%rowtype;
  final_status text;
  adjustment numeric(14, 2) := 0;
  before_snapshot jsonb;
  after_snapshot jsonb;
begin
  select * into reviewer_record from public.employees
  where full_name = trim(p_reviewer_name) and role in ('رئيس المقيمين', 'مطور النظام') and status = 'نشط'
  order by id limit 1;
  if reviewer_record.id is null then
    raise exception 'الاعتراضات يراجعها رئيس المقيمين فقط';
  end if;
  if p_decision not in ('قبول', 'رفض') then
    raise exception 'قرار الاعتراض غير صحيح';
  end if;

  select * into objection_record from public.doctor_call_objections
  where id = p_objection_id for update;
  if objection_record.id is null then raise exception 'الاعتراض غير موجود'; end if;
  if objection_record.status in ('تم التدقيق', 'مرفوض') then raise exception 'تم إغلاق الاعتراض مسبقًا'; end if;

  select * into call_record from public.doctor_calls where id = objection_record.call_id for update;
  before_snapshot := jsonb_build_object('totalApproved', call_record.total_approved, 'objectionStatus', objection_record.status);
  final_status := case when p_decision = 'قبول' then 'تم التدقيق' else 'مرفوض' end;
  adjustment := case when p_decision = 'قبول' then greatest(coalesce(p_adjustment_amount, 0), 0) else 0 end;

  update public.doctor_call_objections set
    status = final_status,
    reviewer_id = reviewer_record.id,
    reviewer_name = reviewer_record.full_name,
    response_note = nullif(trim(p_response_note), ''),
    adjustment_amount = adjustment,
    resolved_at = now(),
    updated_at = now()
  where id = objection_record.id
  returning * into objection_record;

  if adjustment > 0 then
    update public.doctor_calls set
      total_approved = total_approved + adjustment,
      review_note = nullif(trim(p_response_note), ''),
      updated_at = now()
    where id = call_record.id
    returning * into call_record;
  end if;

  after_snapshot := jsonb_build_object(
    'totalApproved', call_record.total_approved,
    'objectionStatus', final_status,
    'adjustmentAmount', adjustment
  );
  insert into public.doctor_call_revisions (
    call_id, editor_id, editor_name, action, before_data, after_data, financial_delta, note
  ) values (
    call_record.id, reviewer_record.id, reviewer_record.full_name, 'تسوية اعتراض',
    before_snapshot, after_snapshot, adjustment, nullif(trim(p_response_note), '')
  );
  insert into public.audit_logs (actor_id, action, entity_type, entity_id, before_data, after_data)
  values (reviewer_record.id, 'تسوية اعتراض', 'doctor_call_objection', objection_record.id::text, before_snapshot, after_snapshot);

  return jsonb_build_object(
    'id', objection_record.id,
    'status', final_status,
    'reviewerName', reviewer_record.full_name,
    'responseNote', objection_record.response_note,
    'adjustmentAmount', adjustment,
    'totalApproved', call_record.total_approved
  );
end;
$$;

do $$
begin
  if exists (select 1 from pg_namespace where nspname = 'storage') then
    insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
    values (
      'consultation-evidence', 'consultation-evidence', false, 5242880,
      array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
    )
    on conflict (id) do update
    set public = false,
        file_size_limit = excluded.file_size_limit,
        allowed_mime_types = excluded.allowed_mime_types;
  end if;
end $$;

alter table public.doctor_call_consultations enable row level security;
alter table public.doctor_call_revisions enable row level security;
alter table public.doctor_call_deliveries enable row level security;
alter table public.doctor_call_objections enable row level security;

revoke all on table
  public.doctor_call_consultations,
  public.doctor_call_revisions,
  public.doctor_call_deliveries,
  public.doctor_call_objections
from anon, authenticated;
grant all on table
  public.doctor_call_consultations,
  public.doctor_call_revisions,
  public.doctor_call_deliveries,
  public.doctor_call_objections
to service_role;
revoke all on function public.save_resident_work_log(text, text, date, integer, integer, integer, integer, integer, integer, text, jsonb) from public, anon, authenticated;
grant execute on function public.save_resident_work_log(text, text, date, integer, integer, integer, integer, integer, integer, text, jsonb) to service_role;
revoke all on function public.resolve_doctor_call_objection(bigint, text, text, text, numeric) from public, anon, authenticated;
grant execute on function public.resolve_doctor_call_objection(bigint, text, text, text, numeric) to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.app_schema_migrations (version)
values ('202608110004_resident_workflow')
on conflict (version) do nothing;
